version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py
  
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

formats:
  - pdf

# Build from the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py
#
#   # Explicitly set the version of Python and its requirements
#   python:
#     install:
#         - requirements: docs/requirements.txt
