[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Flow360Documentation"
authors = [{name = "Flexcompute Inc.", email = "support@flexcompute.com"}]
dynamic = ["version", "description"]
